@echo off
set SOLUTION_DIR=%~1
set PLATFORM=%~2
set CONFIGURATION=%~3
set CONFIGURATION=%CONFIGURATION: JIT=%
set OUT_DIR=%~4
xcopy /y "%SOLUTION_DIR%%PLATFORM%\%CONFIGURATION%\SDL2.dll" "%OUT_DIR%"
