.TH SheepShaver 1 "April, 2000"
.SH NAME
SheepShaver \- Macintosh emulator
.SH SYNOPSIS
.B SheepShaver
[\-display
.IR display-name ]
.SH DESCRIPTION
.B SheepShaver
is a Macintosh emulator for PowerPC-based Linux systems.
For more information, see the included documentation.
.SH OPTIONS
.TP
.BI "\-display " display-name
specifies the display to use; see
.BR X (1)
.SH FILES
.TP
.I ~/.sheepshaver_prefs
User-specific configuration file.
.TP
.I ~/.sheeshaver_nvram
Contents of Mac non-volatile RAM.
.SH SEE ALSO
http://www.sheepshaver.com/ (Official SheepShaver homepage)
.SH AUTHORS
Christian Bauer <Christian.Bauer@uni-mainz.de>
.br
Marc Hellwig <Marc.Hellwig@uni-mainz.de>
