#ifndef NATIVE_FLAGS_X86_H
#define NATIVE_FLAGS_X86_H

/* Native integer code conditions */
enum {
	NATIVE_CC_HI = 7,
	NATIVE_CC_LS = 6,
	NATIVE_CC_CC = 3,
	NATIVE_CC_CS = 2,
	NATIVE_CC_NE = 5,
	NATIVE_CC_EQ = 4,
	NATIVE_CC_VC = 11,
	NATIVE_CC_VS = 10,
	NATIVE_CC_PL = 9,
	NATIVE_CC_MI = 8,
	NATIVE_CC_GE = 13,
	NATIVE_CC_LT = 12,
	NATIVE_CC_GT = 15,
	NATIVE_CC_LE = 14
};

#endif /* NATIVE_FLAGS_X86_H */
